"""empty message

Revision ID: 88cebcdf450a
Revises: 
Create Date: 2018-08-27 20:07:50.362399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88cebcdf450a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scrape_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('scrape_price', sa.DECIMAL(), nullable=False),
    sa.Column('scrape_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scrape_id'], ['scrape.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrape_details')
    op.drop_table('scrape')
    # ### end Alembic commands ###
